/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables


import emented.jooq.main.Public
import emented.jooq.main.keys.EMPLOYEE_PKEY
import emented.jooq.main.keys.EMPLOYEE__EMPLOYEE_ORGANIZATION_ID_FKEY
import emented.jooq.main.tables.Organization.OrganizationPath
import emented.jooq.main.tables.records.EmployeeRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Employee(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, EmployeeRecord>?,
    parentPath: InverseForeignKey<out Record, EmployeeRecord>?,
    aliased: Table<EmployeeRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<EmployeeRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.employee</code>
         */
        val EMPLOYEE: Employee = Employee()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<EmployeeRecord> = EmployeeRecord::class.java

    /**
     * The column <code>public.employee.id</code>.
     */
    val ID: TableField<EmployeeRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.employee.name</code>.
     */
    val NAME: TableField<EmployeeRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.employee.organization_id</code>.
     */
    val ORGANIZATION_ID: TableField<EmployeeRecord, Long?> = createField(DSL.name("organization_id"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<EmployeeRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<EmployeeRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<EmployeeRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.employee</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.employee</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.employee</code> table reference
     */
    constructor(): this(DSL.name("employee"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, EmployeeRecord>?, parentPath: InverseForeignKey<out Record, EmployeeRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, EMPLOYEE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class EmployeePath : Employee, Path<EmployeeRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, EmployeeRecord>?, parentPath: InverseForeignKey<out Record, EmployeeRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<EmployeeRecord>): super(alias, aliased)
        override fun `as`(alias: String): EmployeePath = EmployeePath(DSL.name(alias), this)
        override fun `as`(alias: Name): EmployeePath = EmployeePath(alias, this)
        override fun `as`(alias: Table<*>): EmployeePath = EmployeePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<EmployeeRecord, Long?> = super.getIdentity() as Identity<EmployeeRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<EmployeeRecord> = EMPLOYEE_PKEY
    override fun getReferences(): List<ForeignKey<EmployeeRecord, *>> = listOf(EMPLOYEE__EMPLOYEE_ORGANIZATION_ID_FKEY)

    private lateinit var _organization: OrganizationPath

    /**
     * Get the implicit join path to the <code>public.organization</code> table.
     */
    fun organization(): OrganizationPath {
        if (!this::_organization.isInitialized)
            _organization = OrganizationPath(this, EMPLOYEE__EMPLOYEE_ORGANIZATION_ID_FKEY, null)

        return _organization;
    }

    val organization: OrganizationPath
        get(): OrganizationPath = organization()
    override fun `as`(alias: String): Employee = Employee(DSL.name(alias), this)
    override fun `as`(alias: Name): Employee = Employee(alias, this)
    override fun `as`(alias: Table<*>): Employee = Employee(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Employee = Employee(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Employee = Employee(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Employee = Employee(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Employee = Employee(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Employee = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Employee = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Employee = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Employee = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Employee = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Employee = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Employee = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Employee = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Employee = where(DSL.notExists(select))
}
