/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables


import emented.jooq.main.Public
import emented.jooq.main.keys.EMPLOYEE__EMPLOYEE_ORGANIZATION_ID_FKEY
import emented.jooq.main.keys.ORGANIZATION_PKEY
import emented.jooq.main.tables.Employee.EmployeePath
import emented.jooq.main.tables.records.OrganizationRecord

import java.time.OffsetDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Organization(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, OrganizationRecord>?,
    parentPath: InverseForeignKey<out Record, OrganizationRecord>?,
    aliased: Table<OrganizationRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<OrganizationRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.organization</code>
         */
        val ORGANIZATION: Organization = Organization()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<OrganizationRecord> = OrganizationRecord::class.java

    /**
     * The column <code>public.organization.id</code>.
     */
    val ID: TableField<OrganizationRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.organization.name</code>.
     */
    val NAME: TableField<OrganizationRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.organization.x_coordinate</code>.
     */
    val X_COORDINATE: TableField<OrganizationRecord, Long?> = createField(DSL.name("x_coordinate"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.organization.y_coordinate</code>.
     */
    val Y_COORDINATE: TableField<OrganizationRecord, Double?> = createField(DSL.name("y_coordinate"), SQLDataType.DOUBLE.nullable(false), this, "")

    /**
     * The column <code>public.organization.annual_turnover</code>.
     */
    val ANNUAL_TURNOVER: TableField<OrganizationRecord, Int?> = createField(DSL.name("annual_turnover"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.organization.type</code>.
     */
    val TYPE: TableField<OrganizationRecord, String?> = createField(DSL.name("type"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.organization.official_address_zip</code>.
     */
    val OFFICIAL_ADDRESS_ZIP: TableField<OrganizationRecord, String?> = createField(DSL.name("official_address_zip"), SQLDataType.VARCHAR(6), this, "")

    /**
     * The column <code>public.organization.created_at</code>.
     */
    val CREATED_AT: TableField<OrganizationRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<OrganizationRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<OrganizationRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<OrganizationRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.organization</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.organization</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.organization</code> table reference
     */
    constructor(): this(DSL.name("organization"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, OrganizationRecord>?, parentPath: InverseForeignKey<out Record, OrganizationRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ORGANIZATION, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class OrganizationPath : Organization, Path<OrganizationRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, OrganizationRecord>?, parentPath: InverseForeignKey<out Record, OrganizationRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<OrganizationRecord>): super(alias, aliased)
        override fun `as`(alias: String): OrganizationPath = OrganizationPath(DSL.name(alias), this)
        override fun `as`(alias: Name): OrganizationPath = OrganizationPath(alias, this)
        override fun `as`(alias: Table<*>): OrganizationPath = OrganizationPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<OrganizationRecord, Long?> = super.getIdentity() as Identity<OrganizationRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<OrganizationRecord> = ORGANIZATION_PKEY

    private lateinit var _employee: EmployeePath

    /**
     * Get the implicit to-many join path to the <code>public.employee</code>
     * table
     */
    fun employee(): EmployeePath {
        if (!this::_employee.isInitialized)
            _employee = EmployeePath(this, null, EMPLOYEE__EMPLOYEE_ORGANIZATION_ID_FKEY.inverseKey)

        return _employee;
    }

    val employee: EmployeePath
        get(): EmployeePath = employee()
    override fun `as`(alias: String): Organization = Organization(DSL.name(alias), this)
    override fun `as`(alias: Name): Organization = Organization(alias, this)
    override fun `as`(alias: Table<*>): Organization = Organization(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Organization = Organization(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Organization = Organization(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Organization = Organization(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Organization = Organization(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Organization = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Organization = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Organization = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Organization = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Organization = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Organization = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Organization = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Organization = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Organization = where(DSL.notExists(select))
}
