/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.keys


import emented.jooq.main.tables.Employee
import emented.jooq.main.tables.Organization
import emented.jooq.main.tables.records.EmployeeRecord
import emented.jooq.main.tables.records.OrganizationRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val EMPLOYEE_PKEY: UniqueKey<EmployeeRecord> = Internal.createUniqueKey(Employee.EMPLOYEE, DSL.name("employee_pkey"), arrayOf(Employee.EMPLOYEE.ID), true)
val ORGANIZATION_PKEY: UniqueKey<OrganizationRecord> = Internal.createUniqueKey(Organization.ORGANIZATION, DSL.name("organization_pkey"), arrayOf(Organization.ORGANIZATION.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val EMPLOYEE__EMPLOYEE_ORGANIZATION_ID_FKEY: ForeignKey<EmployeeRecord, OrganizationRecord> = Internal.createForeignKey(Employee.EMPLOYEE, DSL.name("employee_organization_id_fkey"), arrayOf(Employee.EMPLOYEE.ORGANIZATION_ID), emented.jooq.main.keys.ORGANIZATION_PKEY, arrayOf(Organization.ORGANIZATION.ID), true)
