/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records


import emented.jooq.main.tables.Employee

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class EmployeeRecord() : UpdatableRecordImpl<EmployeeRecord>(Employee.EMPLOYEE) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var organizationId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised EmployeeRecord
     */
    constructor(id: Long? = null, name: String? = null, organizationId: Long? = null): this() {
        this.id = id
        this.name = name
        this.organizationId = organizationId
        resetChangedOnNotNull()
    }
}
