/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records


import emented.jooq.main.tables.Organization

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class OrganizationRecord() : UpdatableRecordImpl<OrganizationRecord>(Organization.ORGANIZATION) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var xCoordinate: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var yCoordinate: Double?
        set(value): Unit = set(3, value)
        get(): Double? = get(3) as Double?

    open var annualTurnover: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var type: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var officialAddressZip: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(7, value)
        get(): OffsetDateTime? = get(7) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised OrganizationRecord
     */
    constructor(id: Long? = null, name: String? = null, xCoordinate: Long? = null, yCoordinate: Double? = null, annualTurnover: Int? = null, type: String? = null, officialAddressZip: String? = null, createdAt: OffsetDateTime? = null): this() {
        this.id = id
        this.name = name
        this.xCoordinate = xCoordinate
        this.yCoordinate = yCoordinate
        this.annualTurnover = annualTurnover
        this.type = type
        this.officialAddressZip = officialAddressZip
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
