/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.references


import emented.jooq.main.tables.Employee
import emented.jooq.main.tables.Organization



/**
 * The table <code>public.employee</code>.
 */
val EMPLOYEE: Employee = Employee.EMPLOYEE

/**
 * The table <code>public.organization</code>.
 */
val ORGANIZATION: Organization = Organization.ORGANIZATION
